site:
  name: Trafalgar Logistics
  site: 'https://trafalgarlogistics.co.za'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

metadata:
  title:
    default: Trafalgar Logistics
    template: '%s — Trafalgar Logistics'
  description: "Transport and logistics company based in South Africa, covering critical routes in Zimbabwe, Zambia, and the DRC. Specialists in high-value metals and minerals transport."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Trafalgar Logistics
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
